# Generated by Django 3.2.5 on 2021-10-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Type in your ethereum address?')),
                ('post_id', models.IntegerField(verbose_name='Input post id')),
            ],
        ),
    ]
